package com.loyaltyworks.keshavcement.model
import com.squareup.moshi.JsonClass

import com.squareup.moshi.Json
import java.io.Serializable

/*Redemption Planner Request*/
@JsonClass(generateAdapter = true)
data class PlannerRequest(
    @Json(name = "ActionType")
    val actionType: String? = null,
    @Json(name = "ActorId")
    val actorId: String? = null,
    @Json(name = "StartIndex")
    val startIndex: Int? = null,
    @Json(name = "PageSize")
    val pageSize: Int? = null,
    @Json(name = "PartyLoyaltyID")
    val partyLoyaltyID: String? = null,
    @Json(name = "Domain")
    val domain: String? = null
)

/*Redemption Planner Response*/
@JsonClass(generateAdapter = true)
data class PlannerResponse(
    @Json(name = "objCatalogueList")
    val objCatalogueList: List<ObjCatalogues>? = null,
    @Json(name = "returnMessage")
    val returnMessage: Any? = null,
    @Json(name = "returnValue")
    val returnValue: Int? = null,
    @Json(name = "totalRecords")
    val totalRecords: Int? = null
)

@JsonClass(generateAdapter = true)
data class ObjCatalogues(
    @Json(name = "actionType")
    val actionType: Int? = null,
    @Json(name = "activeStatus")
    val activeStatus: Boolean? = null,
    @Json(name = "actorId")
    val actorId: Int? = null,
    @Json(name = "actorRole")
    val actorRole: Any? = null,
    @Json(name = "actualRedemptionDate")
    val actualRedemptionDate: String? = null,
    @Json(name = "additionalRemarks")
    val additionalRemarks: Any? = null,
    @Json(name = "approverName")
    val approverName: Any? = null,
    @Json(name = "averageEarning")
    val averageEarning: String? = null,
    @Json(name = "avgExpDate")
    val avgExpDate: String? = null,
    @Json(name = "avgGreaterExpDate")
    val avgGreaterExpDate: String? = null,
    @Json(name = "avgLesserExpDate")
    val avgLesserExpDate: String? = null,
    @Json(name = "barcode")
    val barcode: Any? = null,
    @Json(name = "brandTermsAndConditions")
    val brandTermsAndConditions: Any? = null,
    @Json(name = "cashPerUnit")
    val cashPerUnit: Int? = null,
    @Json(name = "cashValue")
    val cashValue: Int? = null,
    @Json(name = "catalogueBrandCode")
    val catalogueBrandCode: Any? = null,
    @Json(name = "catalogueBrandDesc")
    val catalogueBrandDesc: Any? = null,
    @Json(name = "catalogueBrandId")
    val catalogueBrandId: Int? = null,
    @Json(name = "catalogueBrandName")
    val catalogueBrandName: Any? = null,
    @Json(name = "catalogueId")
    val catalogueId: Int? = null,
    @Json(name = "catalogueType")
    val catalogueType: Int? = null,
    @Json(name = "catalougeBrandName")
    val catalougeBrandName: Any? = null,
    @Json(name = "categoryID")
    val categoryID: Int? = null,
    @Json(name = "categoryParentID")
    val categoryParentID: Int? = null,
    @Json(name = "catogoryId")
    val catogoryId: Int? = null,
    @Json(name = "catogoryImage")
    val catogoryImage: Any? = null,
    @Json(name = "catogoryName")
    val catogoryName: Any? = null,
    @Json(name = "color_Code")
    val colorCode: Any? = null,
    @Json(name = "color_Id")
    val colorId: Int? = null,
    @Json(name = "color_Name")
    val colorName: Any? = null,
    @Json(name = "commandName")
    val commandName: Any? = null,
    @Json(name = "countryCurrencyCode")
    val countryCurrencyCode: Any? = null,
    @Json(name = "countryID")
    val countryID: Int? = null,
    @Json(name = "createdBy")
    val createdBy: Any? = null,
    @Json(name = "createdDate")
    val createdDate: Any? = null,
    @Json(name = "dailyAvgCash")
    val dailyAvgCash: String? = null,
    @Json(name = "deliveryType")
    val deliveryType: Any? = null,
    @Json(name = "dreamGiftId")
    val dreamGiftId: Int? = null,
    @Json(name = "expectedDelivery")
    val expectedDelivery: Any? = null,
    @Json(name = "expiryDate")
    val expiryDate: Any? = null,
    @Json(name = "expiryOn")
    val expiryOn: Int? = null,
    @Json(name = "fromDate")
    val fromDate: Any? = null,
    @Json(name = "greaterAvgCash")
    val greaterAvgCash: String? = null,
    @Json(name = "hasPartialPayment")
    val hasPartialPayment: Boolean? = null,
    @Json(name = "isActive")
    val isActive: Boolean? = null,
    @Json(name = "isApproved")
    val isApproved: Boolean? = null,
    @Json(name = "isCash")
    val isCash: Boolean? = null,
    @Json(name = "isPlanner")
    val isPlanner: Boolean? = null,
    @Json(name = "isPopularCount")
    val isPopularCount: Int? = null,
    @Json(name = "jFromDate")
    val jFromDate: Any? = null,
    @Json(name = "jRedemptionDate")
    val jRedemptionDate: Any? = null,
    @Json(name = "jToDate")
    val jToDate: Any? = null,
    @Json(name = "lesserAvgCash")
    val lesserAvgCash: String? = null,
    @Json(name = "locationId")
    val locationId: Int? = null,
    @Json(name = "loyaltyId")
    val loyaltyId: String? = null,
    @Json(name = "mSQA")
    val mSQA: Int? = null,
    @Json(name = "max_points")
    val maxPoints: Any? = null,
    @Json(name = "memberName")
    val memberName: Any? = null,
    @Json(name = "merchantId")
    val merchantId: Int? = null,
    @Json(name = "merchantName")
    val merchantName: Any? = null,
    @Json(name = "min_points")
    val minPoints: Any? = null,
    @Json(name = "minimumStockQunty")
    val minimumStockQunty: Int? = null,
    @Json(name = "mobile")
    val mobile: Any? = null,
    @Json(name = "modelId")
    val modelId: Int? = null,
    @Json(name = "modelName")
    val modelName: Any? = null,
    @Json(name = "multipleRedIds")
    val multipleRedIds: Any? = null,
    @Json(name = "noOfPointsDebit")
    val noOfPointsDebit: Int? = null,
    @Json(name = "noOfQuantity")
    val noOfQuantity: Int? = null,
    @Json(name = "partialPaymentCash")
    val partialPaymentCash: Int? = null,
    @Json(name = "plannerStatus")
    val plannerStatus: Any? = null,
    @Json(name = "pointBalance")
    val pointBalance: Int? = null,
    @Json(name = "pointRedem")
    val pointRedem: Int? = null,
    @Json(name = "pointReqToAcheiveProduct")
    val pointReqToAcheiveProduct: Int? = null,
    @Json(name = "pointsPerUnit")
    val pointsPerUnit: Int? = null,
    @Json(name = "pointsRequired")
    val pointsRequired: Int? = null,
    @Json(name = "productCode")
    val productCode: String? = null,
    @Json(name = "productDesc")
    val productDesc: String? = null,
    @Json(name = "productImage")
    val productImage: String? = null,
    @Json(name = "productImageServerPath")
    val productImageServerPath: Any? = null,
    @Json(name = "productName")
    val productName: String? = null,
    @Json(name = "product_type")
    val productType: Int? = null,
    @Json(name = "redeemableAverageEarning")
    val redeemableAverageEarning: String? = null,
    @Json(name = "redeemableAverageEarning12")
    val redeemableAverageEarning12: Int? = null,
    @Json(name = "redeemableAverageEarning6")
    val redeemableAverageEarning6: Int? = null,
    @Json(name = "redeemableEncashBalance")
    val redeemableEncashBalance: Int? = null,
    @Json(name = "redeemablePointBalance")
    val redeemablePointBalance: Int? = null,
    @Json(name = "redemptionDate")
    val redemptionDate: Any? = null,
    @Json(name = "redemptionId")
    val redemptionId: Int? = null,
    @Json(name = "redemptionPlannerId")
    val redemptionPlannerId: Int? = null,
    @Json(name = "redemptionRefno")
    val redemptionRefno: Any? = null,
    @Json(name = "redemptionStatus")
    val redemptionStatus: Any? = null,
    @Json(name = "redemptionTypeId")
    val redemptionTypeId: Int? = null,
    @Json(name = "segmentDetails")
    val segmentDetails: Any? = null,
    @Json(name = "selectedStatus")
    val selectedStatus: Int? = null,
    @Json(name = "status")
    val status: Int? = null,
    @Json(name = "subCategoryID")
    val subCategoryID: Int? = null,
    @Json(name = "subCategoryName")
    val subCategoryName: Any? = null,
    @Json(name = "termsCondition")
    val termsCondition: Any? = null,
    @Json(name = "toDate")
    val toDate: Any? = null,
    @Json(name = "totalCash")
    val totalCash: Int? = null,
    @Json(name = "total_Row")
    val totalRow: Int? = null,
    @Json(name = "userAccess")
    val userAccess: Int? = null,
    @Json(name = "vendorId")
    val vendorId: Int? = null,
    @Json(name = "vendorName")
    val vendorName: String? = null,
    @Json(name = "is_Redeemable")
    val isRedeemable: Int? = null
): Serializable

/* Remove Planner Request  */
@JsonClass(generateAdapter = true)
data class RemovePlannerRequest(
    @Json(name = "ActionType")
    val actionType: Int? = null,
    @Json(name = "ActorId")
    val actorId: String? = null,
    @Json(name = "RedemptionPlannerId")
    val redemptionPlannerId: Int? = null,
    @Json(name = "PartyLoyaltyID")
    val partyLoyaltyID: String? = null
)

/* Remove Planner Response  */
@JsonClass(generateAdapter = true)
data class RemovePlannerResponse(
    @Json(name = "objCatalogueList")
    val objCatalogueList: Any? = null,
    @Json(name = "returnMessage")
    val returnMessage: Any? = null,
    @Json(name = "returnValue")
    val returnValue: Int? = null,
    @Json(name = "totalRecords")
    val totalRecords: Int? = null
)